<Project Sdk="Godot.NET.Sdk/4.8.0-dev">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="assets\.DS_Store" />
    <Content Include="assets\Shaders\Compute\FSL\indirect_dispatch_helpers.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\mesh\cbs\bisector_defs.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\mesh\cbs\bisector_util.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\mesh\cbs\cbs_indirect_helpers.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\mesh\cbs\cbtrees_util.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\mesh\cbs\cbtree_defs.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\mesh\cbs\classify_bisectors.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\mesh\cbs\update_bisectors.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\mesh\cbs\update_cbtree.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\mesh\cbtree_kernels.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\mesh\mesh_common.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\mesh\mesh_gen.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\ocean\complex.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\ocean\fft_optim.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\ocean\mipmaps.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\ocean\old\fft.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\ocean\old\tessendorf_funcs.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\ocean\shared_resources.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\ocean\spectrums.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\ocean\spreadings.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\ocean\sum_of_sines\sum_of_sines.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\ocean\temp.fsl" />
    <Content Include="assets\Shaders\Compute\FSL\ocean\tess_funcs_optim.fsl" />
    <Content Include="assets\Textures\Epic_BlueSunset_EquiRect_flat.png" />
    <Content Include="assets\Textures\Epic_BlueSunset_EquiRect_flat.png.import" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Scenes\" />
  </ItemGroup>
</Project>