// <auto-generated>
// Generated by bindings/generate_csharp_bindings.py from bindings/csharp_manifest.json.
// Do not edit by hand: edit the manifest and rebuild (scons).
// </auto-generated>
using Godot;

namespace FluxxiShaderLang;

/// <summary>Wraps a GDExtension object in the most-derived C# wrapper for its Godot class.</summary>
public static class ComputeGroupFactory
{
    public static ComputeGroup Wrap(GodotObject inner) => inner == null ? null : new ComputeGroup(inner);
}
