// <auto-generated>
// Generated by bindings/generate_csharp_bindings.py from bindings/csharp_manifest.json.
// Do not edit by hand: edit the manifest and rebuild (scons).
// </auto-generated>
using Godot;

namespace FluxxiShaderLang;

/// <summary>C# wrapper for the "ComputeGroup" GDExtension class.</summary>
public partial class ComputeGroup
{
    public static readonly StringName GDClassName = "ComputeGroup";

    /// <summary>The underlying GDExtension object; pass this to Godot APIs.</summary>
    public RefCounted Inner { get; }

    public ComputeGroup(GodotObject inner)
    {
        Inner = (RefCounted)inner;
    }

    public ComputeGroup() : this(ClassDB.Instantiate(GDClassName).AsGodotObject()) { }

    public static implicit operator Variant(ComputeGroup wrapper) => wrapper?.Inner ?? default;

    public void PrintInfo() => Inner.Call(MethodName.PrintInfo);

    public ComputeKernel GetKernel(StringName kernelName) => ComputeKernelFactory.Wrap(Inner.Call(MethodName.GetKernel, kernelName).AsGodotObject());

    public void AssignResource(FSLResource resource, StringName resourceName) => Inner.Call(MethodName.AssignResource, resource?.Inner, resourceName);

    public void SetSpecializationConstant(StringName specConstant, Variant value) => Inner.Call(MethodName.SetSpecializationConstant, specConstant, value);

    public void Dispatch(StringName kernelName, uint xInvocations, uint yInvocations, uint zInvocations, Godot.Collections.Dictionary<StringName, Variant> pushConstants = null) => Inner.Call(MethodName.Dispatch, kernelName, xInvocations, yInvocations, zInvocations, pushConstants ?? new Godot.Collections.Dictionary<StringName, Variant>());

    public void DispatchWorkgroups(StringName kernelName, uint xWorkgroups, uint yWorkgroups, uint zWorkgroups, Godot.Collections.Dictionary<StringName, Variant> pushConstants = null) => Inner.Call(MethodName.DispatchWorkgroups, kernelName, xWorkgroups, yWorkgroups, zWorkgroups, pushConstants ?? new Godot.Collections.Dictionary<StringName, Variant>());

    public void DispatchIndirect(StringName kernelName, FSLBuffer commandBuffer, uint offset, Godot.Collections.Dictionary<StringName, Variant> pushConstants = null) => Inner.Call(MethodName.DispatchIndirect, kernelName, commandBuffer?.Inner, offset, pushConstants ?? new Godot.Collections.Dictionary<StringName, Variant>());

    public FSLStorageBuffer GetStorageBuffer(StringName bufferName) => (FSLStorageBuffer)FSLResourceFactory.Wrap(Inner.Call(MethodName.GetStorageBuffer, bufferName).AsGodotObject());

    public FSLUniformBuffer GetUniformBuffer(StringName bufferName) => (FSLUniformBuffer)FSLResourceFactory.Wrap(Inner.Call(MethodName.GetUniformBuffer, bufferName).AsGodotObject());

    public FSLVertexBuffer GetVertexBuffer(StringName bufferName) => (FSLVertexBuffer)FSLResourceFactory.Wrap(Inner.Call(MethodName.GetVertexBuffer, bufferName).AsGodotObject());

    public FSLIndexBuffer GetIndexBuffer(StringName bufferName) => (FSLIndexBuffer)FSLResourceFactory.Wrap(Inner.Call(MethodName.GetIndexBuffer, bufferName).AsGodotObject());

    public FSLTexture2D GetTexture2D(StringName textureName) => (FSLTexture2D)FSLResourceFactory.Wrap(Inner.Call(MethodName.GetTexture2D, textureName).AsGodotObject());

    public FSLTexture2DArray GetTexture2DArray(StringName textureName) => (FSLTexture2DArray)FSLResourceFactory.Wrap(Inner.Call(MethodName.GetTexture2DArray, textureName).AsGodotObject());

    public FSLSampler2DArray GetSampler2DArray(StringName samplerName) => (FSLSampler2DArray)FSLResourceFactory.Wrap(Inner.Call(MethodName.GetSampler2DArray, samplerName).AsGodotObject());

    public FSLResource GetResource(StringName resourceName) => FSLResourceFactory.Wrap(Inner.Call(MethodName.GetResource, resourceName).AsGodotObject());

    public static class MethodName
    {
        public static readonly StringName PrintInfo = "print_info";
        public static readonly StringName GetKernel = "get_kernel";
        public static readonly StringName AssignResource = "assign_resource";
        public static readonly StringName SetSpecializationConstant = "set_specialization_constant";
        public static readonly StringName Dispatch = "dispatch";
        public static readonly StringName DispatchWorkgroups = "dispatch_workgroups";
        public static readonly StringName DispatchIndirect = "dispatch_indirect";
        public static readonly StringName GetStorageBuffer = "get_storage_buffer";
        public static readonly StringName GetUniformBuffer = "get_uniform_buffer";
        public static readonly StringName GetVertexBuffer = "get_vertex_buffer";
        public static readonly StringName GetIndexBuffer = "get_index_buffer";
        public static readonly StringName GetTexture2D = "get_texture_2d";
        public static readonly StringName GetTexture2DArray = "get_texture_2d_array";
        public static readonly StringName GetSampler2DArray = "get_sampler_2d_array";
        public static readonly StringName GetResource = "get_resource";
    }
}
