// <auto-generated>
// Generated by bindings/generate_csharp_bindings.py from bindings/csharp_manifest.json.
// Do not edit by hand: edit the manifest and rebuild (scons).
// </auto-generated>
using Godot;

namespace FluxxiShaderLang;

/// <summary>C# wrapper for the "ComputePlan" GDExtension class.</summary>
public partial class ComputePlan
{
    public static readonly StringName GDClassName = "ComputePlan";

    /// <summary>The underlying GDExtension object; pass this to Godot APIs.</summary>
    public RefCounted Inner { get; }

    public ComputePlan(GodotObject inner)
    {
        Inner = (RefCounted)inner;
    }

    public ComputePlan() : this(ClassDB.Instantiate(GDClassName).AsGodotObject()) { }

    public static implicit operator Variant(ComputePlan wrapper) => wrapper?.Inner ?? default;

    public static ComputePlan MakeNew(RenderingDevice renderingDevice = null) => ComputePlanFactory.Wrap(ClassDB.ClassCallStatic(GDClassName, MethodName.MakeNew, renderingDevice).AsGodotObject());

    public ComputePlan AddBarrier(bool isTemp = false) => ComputePlanFactory.Wrap(Inner.Call(MethodName.AddBarrier, isTemp).AsGodotObject());

    public ComputePlan AddKernel(ComputeKernel kernel, uint xInvocations, uint yInvocations, uint zInvocations, Godot.Collections.Dictionary<StringName, Variant> pushConstants = null, bool isTemp = false) => ComputePlanFactory.Wrap(Inner.Call(MethodName.AddKernel, kernel?.Inner, xInvocations, yInvocations, zInvocations, pushConstants ?? new Godot.Collections.Dictionary<StringName, Variant>(), isTemp).AsGodotObject());

    public ComputePlan AddKernelWorkgroups(ComputeKernel kernel, uint xWorkgroups, uint yWorkgroups, uint zWorkgroups, Godot.Collections.Dictionary<StringName, Variant> pushConstants = null, bool isTemp = false) => ComputePlanFactory.Wrap(Inner.Call(MethodName.AddKernelWorkgroups, kernel?.Inner, xWorkgroups, yWorkgroups, zWorkgroups, pushConstants ?? new Godot.Collections.Dictionary<StringName, Variant>(), isTemp).AsGodotObject());

    public ComputePlan AddKernelIndirect(ComputeKernel kernel, FSLBuffer commandBuffer, uint offset, Godot.Collections.Dictionary<StringName, Variant> pushConstants = null, bool isTemp = false) => ComputePlanFactory.Wrap(Inner.Call(MethodName.AddKernelIndirect, kernel?.Inner, commandBuffer?.Inner, offset, pushConstants ?? new Godot.Collections.Dictionary<StringName, Variant>(), isTemp).AsGodotObject());

    public void AddPlan(ComputePlan subplan, bool isTemp = false) => Inner.Call(MethodName.AddPlan, subplan?.Inner, isTemp);

    public void Dispatch() => Inner.Call(MethodName.Dispatch);

    public static class MethodName
    {
        public static readonly StringName MakeNew = "make_new";
        public static readonly StringName AddBarrier = "add_barrier";
        public static readonly StringName AddKernel = "add_kernel";
        public static readonly StringName AddKernelWorkgroups = "add_kernel_workgroups";
        public static readonly StringName AddKernelIndirect = "add_kernel_indirect";
        public static readonly StringName AddPlan = "add_plan";
        public static readonly StringName Dispatch = "dispatch";
    }
}
