// <auto-generated>
// Generated by bindings/generate_csharp_bindings.py from bindings/csharp_manifest.json.
// Do not edit by hand: edit the manifest and rebuild (scons).
// </auto-generated>
using Godot;

namespace FluxxiShaderLang;

/// <summary>C# wrapper for the "FSLBuffer" GDExtension class.</summary>
public partial class FSLBuffer : FSLResource
{
    public new static readonly StringName GDClassName = "FSLBuffer";

    public FSLBuffer(GodotObject inner) : base(inner) { }

    public void AddFlag(ulong flag) => Inner.Call(MethodName.AddFlag, flag);

    public void SetFlags(ulong flags) => Inner.Call(MethodName.SetFlags, flags);

    public void RemoveFlag(ulong flag) => Inner.Call(MethodName.RemoveFlag, flag);

    public uint GetSizeBytes() => Inner.Call(MethodName.GetSizeBytes).As<uint>();

    public void CopyTo(FSLBuffer dest, bool allowDifferentSize = true) => Inner.Call(MethodName.CopyTo, dest?.Inner, allowDifferentSize);

    public void CopyBytes(FSLBuffer dest, uint numBytes, uint offsetSrc = 0, uint offsetDest = 0) => Inner.Call(MethodName.CopyBytes, dest?.Inner, numBytes, offsetSrc, offsetDest);

    public new static class MethodName
    {
        public static readonly StringName AddFlag = "add_flag";
        public static readonly StringName SetFlags = "set_flags";
        public static readonly StringName RemoveFlag = "remove_flag";
        public static readonly StringName GetSizeBytes = "get_size_bytes";
        public static readonly StringName CopyTo = "copy_to";
        public static readonly StringName CopyBytes = "copy_bytes";
    }
}
