// <auto-generated>
// Generated by bindings/generate_csharp_bindings.py from bindings/csharp_manifest.json.
// Do not edit by hand: edit the manifest and rebuild (scons).
// </auto-generated>
using Godot;

namespace FluxxiShaderLang;

/// <summary>C# wrapper for the "FSLIndexBuffer" GDExtension class.</summary>
public partial class FSLIndexBuffer : FSLBuffer
{
    public new static readonly StringName GDClassName = "FSLIndexBuffer";

    public FSLIndexBuffer(GodotObject inner) : base(inner) { }

    public FSLIndexBuffer() : this(ClassDB.Instantiate(GDClassName).AsGodotObject()) { }

    public void SetIndexCount(uint numIndices) => Inner.Call(MethodName.SetIndexCount, numIndices);

    public void SetIndexFormat(RenderingDevice.IndexBufferFormat newFormat) => Inner.Call(MethodName.SetIndexFormat, (long)newFormat);

    public void CopyIndices(FSLBuffer dest, uint numIndices = 0, uint offset = 0, uint destOffsetBytes = 0) => Inner.Call(MethodName.CopyIndices, dest?.Inner, numIndices, offset, destOffsetBytes);

    public new static class MethodName
    {
        public static readonly StringName SetIndexCount = "set_index_count";
        public static readonly StringName SetIndexFormat = "set_index_format";
        public static readonly StringName CopyIndices = "copy_indices";
    }
}
