// <auto-generated>
// Generated by bindings/generate_csharp_bindings.py from bindings/csharp_manifest.json.
// Do not edit by hand: edit the manifest and rebuild (scons).
// </auto-generated>
using Godot;

namespace FluxxiShaderLang;

/// <summary>C# wrapper for the "FSLRawResource" GDExtension class.</summary>
public partial class FSLRawResource : FSLResource
{
    public new static readonly StringName GDClassName = "FSLRawResource";

    public FSLRawResource(GodotObject inner) : base(inner) { }

    public FSLRawResource() : this(ClassDB.Instantiate(GDClassName).AsGodotObject()) { }

    public static FSLRawResource FromRid(Rid rid, RenderingDevice.UniformType uniformType) => (FSLRawResource)FSLResourceFactory.Wrap(ClassDB.ClassCallStatic(GDClassName, MethodName.FromRid, rid, (long)uniformType).AsGodotObject());

    public void SetRid(Rid rid) => Inner.Call(MethodName.SetRid, rid);

    public void SetUniformType(RenderingDevice.UniformType uniformType) => Inner.Call(MethodName.SetUniformType, (long)uniformType);

    public RenderingDevice.UniformType GetUniformType() => (RenderingDevice.UniformType)Inner.Call(MethodName.GetUniformType).As<long>();

    public new static class MethodName
    {
        public static readonly StringName FromRid = "from_rid";
        public static readonly StringName SetRid = "set_rid";
        public static readonly StringName SetUniformType = "set_uniform_type";
        public static readonly StringName GetUniformType = "get_uniform_type";
    }
}
