// <auto-generated>
// Generated by bindings/generate_csharp_bindings.py from bindings/csharp_manifest.json.
// Do not edit by hand: edit the manifest and rebuild (scons).
// </auto-generated>
using Godot;

namespace FluxxiShaderLang;

/// <summary>Wraps a GDExtension object in the most-derived C# wrapper for its Godot class.</summary>
public static class FSLResourceFactory
{
    public static FSLResource Wrap(GodotObject inner) => inner?.GetClass() switch
    {
        null => null,
        "FSLRawResource" => new FSLRawResource(inner),
        "FSLStorageBuffer" => new FSLStorageBuffer(inner),
        "FSLUniformBuffer" => new FSLUniformBuffer(inner),
        "FSLVertexBuffer" => new FSLVertexBuffer(inner),
        "FSLIndexBuffer" => new FSLIndexBuffer(inner),
        "FSLTexture2D" => new FSLTexture2D(inner),
        "FSLTexture2DArray" => new FSLTexture2DArray(inner),
        "FSLTextureView" => new FSLTextureView(inner),
        "FSLSampler2DArray" => new FSLSampler2DArray(inner),
        _ => new FSLResource(inner),
    };
}
