// <auto-generated>
// Generated by bindings/generate_csharp_bindings.py from bindings/csharp_manifest.json.
// Do not edit by hand: edit the manifest and rebuild (scons).
// </auto-generated>
using Godot;

namespace FluxxiShaderLang;

/// <summary>C# wrapper for the "FSLSamplerType" GDExtension class.</summary>
public partial class FSLSamplerType : FSLResource
{
    public new static readonly StringName GDClassName = "FSLSamplerType";

    public FSLSamplerType(GodotObject inner) : base(inner) { }
}
