// <auto-generated>
// Generated by bindings/generate_csharp_bindings.py from bindings/csharp_manifest.json.
// Do not edit by hand: edit the manifest and rebuild (scons).
// </auto-generated>
using Godot;

namespace FluxxiShaderLang;

/// <summary>C# wrapper for the "FSLSampler2DArray" GDExtension class.</summary>
public partial class FSLSampler2DArray : FSLSamplerType
{
    public new static readonly StringName GDClassName = "FSLSampler2DArray";

    public FSLSampler2DArray(GodotObject inner) : base(inner) { }

    public FSLSampler2DArray() : this(ClassDB.Instantiate(GDClassName).AsGodotObject()) { }

    public void BindTexture(FSLTexture2DArray texture) => Inner.Call(MethodName.BindTexture, texture?.Inner);

    public new static class MethodName
    {
        public static readonly StringName BindTexture = "bind_texture";
    }
}
