// <auto-generated>
// Generated by bindings/generate_csharp_bindings.py from bindings/csharp_manifest.json.
// Do not edit by hand: edit the manifest and rebuild (scons).
// </auto-generated>
using Godot;

namespace FluxxiShaderLang;

/// <summary>C# wrapper for the "FSLTexture2DArray" GDExtension class.</summary>
public partial class FSLTexture2DArray : FSLTexture
{
    public new static readonly StringName GDClassName = "FSLTexture2DArray";

    public FSLTexture2DArray(GodotObject inner) : base(inner) { }

    public FSLTexture2DArray() : this(ClassDB.Instantiate(GDClassName).AsGodotObject()) { }

    public void SetTexture(uint texWidth, uint texHeight, uint index, Image image = null) => Inner.Call(MethodName.SetTexture, texWidth, texHeight, index, image);

    public void SetTextures(uint texWidth, uint texHeight, uint texCount, Godot.Collections.Array<Image> images = null) => Inner.Call(MethodName.SetTextures, texWidth, texHeight, texCount, images ?? new Godot.Collections.Array<Image>());

    public FSLTextureView GetMipView(uint mipLevel) => (FSLTextureView)FSLResourceFactory.Wrap(Inner.Call(MethodName.GetMipView, mipLevel).AsGodotObject());

    public new static class MethodName
    {
        public static readonly StringName SetTexture = "set_texture";
        public static readonly StringName SetTextures = "set_textures";
        public static readonly StringName GetMipView = "get_mip_view";
    }
}
